config/routes.rb
Rails.application.routes.draw do

  # HomePage
  root to: 'home#index'

  # Articles page/Création de brouillon
  resources :blog, as: :articles, controller: 'articles', only: [:index, :show]
  scope '/draft' do
    get '/', to: 'posts#draft_index', as: :draft_index

    get '/new', to: 'posts#draft', as: :draft_new
    post '/new', to: 'posts#create_draft'

    get '/:id/edit', to: 'posts#edit_draft', as: :edit_draft
    patch '/:id/edit', to: 'posts#update_draft'

    get '/:id/publish', to: 'posts#publish', as: :publish_draft
    get '/:id/unpublish', to: 'posts#unpublish', as: :unpublish_draft
  end
  # Supression des brouillon
  get '/drafts/:id', to: 'drafts#destroy', as: :dra

  #Inscription, connexion et déconnexion des utilisateurs
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: :logout_session
  match '/forgot', to: 'sessions#forgot', as: :forgot, via: [:get, :post]
  match '/password/new', to: 'sessions#password', as: :forgot_success, via: [:get, :post]
  resources :users, only: [:new, :create]

  scope '/profil' do
    get '/', to: 'users#account', as: :profil

    get '/edit', to: 'users#edit', as: :edit_user
    patch '/edit', to: 'users#update'

    get '/:id', to: 'users#show', as: :view_user
  end

  scope '/dashboard', as: :admin do
    get '/', to: 'admin/pages#index', as: :index
    resources :articles, controller: 'admin/posts'
    resources :tutoriels, controller: 'admin/tutoriels'
  end

  scope '/blog' do
    get '/like/:post_id/:user_id', to: 'articles#like', as: :likes
    get '/unlike/:id/:post_id', to: 'articles#unlike', as: :unlikes
    post '/:slug', to: 'articles#create_comment', as: :new_comment
    get '/comment/like/:comment_id/:post_id', to: 'articles#like_comment', as: :like_comment
    get '/comment/unlike/:comment_id/:post_id', to: 'articles#unlike_comment', as: :unlike_comment
  end

  get '/tutoriels/:category_name', to: 'tutoriels#show', as: :category_view
  get '/tutoriels/:category/:title', to: 'tutoriels#show_tutoriel', as: :show_tuto
  resources :tutoriels, only: [:index]
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @posts = Post.where(published: 1)
  end

  def show
    @post = Post.friendly.where(published: 1).find(params[:id])
    if current_user
      @like = Like.where(post_id: @post.id, user_id: current_user.id, commentable: :post).first
    end
    @comment = Comment.new
    @comments = Comment.where(post_id: @post.id, parent_id: 0)
  end

  def like
    post = Post.find(params[:post_id])
    like = Like.where(user_id: current_user.id, post_id: post.id, commentable: :post).first
    if like
      redirect_to article_path(post), error: "Vous aimez dèja cette article"
    else
      Like.create(post_id: params[:post_id], user_id: params[:user_id])
      redirect_to article_path(post), success: "Merci pour votre j'aime"
    end
  end

  def unlike
    like = Like.where(user_id: current_user.id, commentable: :post).first
    post = Post.find(params[:post_id])

    if post.nil?
      redirect_to root_path, error: "Cet article n'existe pas"
    end

    if like
      Like.destroy(params[:id])
      redirect_to article_path(post), success: "Vous n'aimez plus cet article"
    end
  end

  def create_comment
    if current_user
      comment_params = params.require(:comment).permit(:content, :parent_id)
      @comment = Comment.new(comment_params)
      @post = Post.friendly.find(params[:slug])
      @comments = Comment.where(post_id: @post.id, parent_id: 0)
      @comment.post_id = @post.id
      @comment.user_id = current_user.id
      @comment.username = current_user.username
      @comment.email = current_user.email
    else
      comment_params = params.require(:comment).permit(:username, :email, :content, :parent_id)
      @comment = Comment.new(comment_params)
      @post = Post.friendly.find(params[:slug])
      @comments = Comment.where(post_id: @post.id, parent_id: 0)
      @comment.post_id = @post.id
      @comment.user_id = false
    end

    if @comment.valid?
      @comment.save
      redirect_to article_path(@post), success: "Le commentaire a bien été posté"
    else
      render :show
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<div class="comment" id="<%= comment.id %>">
  <div class="avatar">
    <img src="https://www.grafikart.fr/uploads/avatars/110/109584.jpg">
  </div>
  <div class="right">
    <div class="author">
      <%= comment.username %> - <%= link_to 'Répondre', '#', class: 'reply', data: {id: comment.id} %> -
    </div>
    <div class="content" id="comment_content">
      <%= comment.content %>
    </div>
  </div>
</div>

app/views/articles/_reply.html.erb
<div class="comment" style="margin-left: 50px;">
  <div class="avatar">
    <img src="https://www.grafikart.fr/uploads/avatars/110/109584.jpg">
  </div>
  <div class="right">
    <div class="author">
      <%= reply.username %>
    </div>
    <div class="content">
      <%= reply.content %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div>
  <h2>Blog</h2>
</div>
<div>
  <%= link_to 'Ajouter un article', draft_new_path, class: 'btn btn-primary' %>
</div>

<div class="blog">
  <% @posts.each do |post| %>
      <div class="col-sm-3">
        <article class="article">
          <header>
            <span class="title"><%= link_to post.title, article_path(post) %></span>
          </header>
        </article>
      </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="post">
  <article>
    <h2><%= @post.title %></h2>
    <div class="list">
    <span class="author">
      <%= link_to view_user_path(@post.user.id) do %>
          <i class="glyphicon glyphicon-user"></i>
          <%= @post.user.username %>
      <% end %>
    </span>
      <span class="like">
      <span class="count" title="<%= @post.likes.count %> personne aime l'article">
        <i class="glyphicon glyphicon-thumbs-up"></i>
        <%= @post.likes.count %>
      </span>
        <% if current_user %>
        <% if @like %>
          <%= link_to unlikes_path(@like.id, @post.id) do %>
              Je n'aime plus
          <% end %>
        <% else %>
          <%= link_to likes_path(@post.id, current_user.id) do %>
            J'aime
          <% end %>
        <% end %>
      <% end %>
    </span>
    </div>
    <div class="content">
      <%= @post.content %>
    </div>
  </article>
  <div class="post-form">
    <h4>
      <%= @post.comments.count %> Commentaire<% if @post.comments.count > 1 %>s<% end %>
    </h4>

    <% if @comment.errors.any? %>
        <div class="alert alert-danger">
          <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </div>
    <% end %>

    <div id="forms">
      <%= form_for @comment, url: new_comment_path(@post) do |f| %>
          <span class="cancel"><a href="#" id="cancel"></a></span>
          <% if current_user.nil? %>
              <div class="form-group">
                <%= f.label :username, "Pseudo" %>
                <%= f.text_field :username, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email, "Email" %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
          <% end %>
          <div class="form-group">
            <%= f.label :content, "Contenu" %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
          <%= f.hidden_field :parent_id %>
          <div class="form-group">
            <%= f.submit 'Envoyer', class: 'btn btn-primary' %>
          </div>
      <% end %>
    </div>
    <div class="comment-list">
      <% @comments.each do |comment| %>
          <%= render 'comment', comment: comment, post: @post %>
          <% Comment.where(post_id: @post.id, parent_id: comment.id).each do |rep| %>
              <%= render 'reply', reply: rep %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>