config/routes.rb
Rails.application.routes.draw do

  # HomePage
  root to: 'home#index'

  # Articles page/Création de brouillon
  resources :blog, as: :articles, controller: 'articles', only: [:index, :show]
  scope '/draft' do
    get '/', to: 'posts#draft_index', as: :draft_index

    get '/new', to: 'posts#draft', as: :draft_new
    post '/new', to: 'posts#create_draft'

    get '/:id/edit', to: 'posts#edit_draft', as: :edit_draft
    patch '/:id/edit', to: 'posts#update_draft'

    get '/:id/publish', to: 'posts#publish', as: :publish_draft
    get '/:id/unpublish', to: 'posts#unpublish', as: :unpublish_draft
  end
  # Supression des brouillon
  get '/drafts/:id', to: 'drafts#destroy', as: :dra

  #Inscription, connexion et déconnexion des utilisateurs
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: :logout_session
  match '/forgot', to: 'sessions#forgot', as: :forgot, via: [:get, :post]
  match '/password/new', to: 'sessions#password', as: :forgot_success, via: [:get, :post]
  resources :users, only: [:new, :create]

  scope '/profil' do
    get '/', to: 'users#account', as: :profil

    get '/edit', to: 'users#edit', as: :edit_user
    patch '/edit', to: 'users#update'

    get '/:id', to: 'users#show', as: :view_user
  end

  scope '/dashboard', as: :admin do
    get '/', to: 'admin/pages#index', as: :index
    resources :articles, controller: 'admin/posts'
    resources :tutoriels, controller: 'admin/tutoriels'
  end

  scope '/blog' do
    get '/like/:post_id/:user_id', to: 'articles#like', as: :likes
    get '/unlike/:id/:post_id', to: 'articles#unlike', as: :unlikes
    post '/:slug', to: 'articles#create_comment', as: :new_comment
    get '/comment/like/:comment_id/:post_id', to: 'articles#like_comment', as: :like_comment
    get '/comment/unlike/:comment_id/:post_id', to: 'articles#unlike_comment', as: :unlike_comment
  end

  get '/tutoriels/:category_name', to: 'tutoriels#show', as: :category_view
  get '/tutoriels/:category/:title', to: 'tutoriels#show_tutoriel', as: :show_tuto
  resources :tutoriels, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user, optional: true
  has_many :likes
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    post_params = params.require(:post).permit(:title, :content)

    if @post.update(post_params)
      redirect_to admin_article_index_path
    else
      render :edit
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :loggedIn
  skip_before_action :verify_authenticity_token

  def draft_index
    loggedIn
    @draft = Post.where(user_id: current_user.id)
  end

  def draft
    notAuthorize
    @draft = Post.new
  end

  def create_draft
    post_params = params.require(:post).permit(:title, :content)

    @draft = Post.new(post_params)

    if @draft.valid?
      @draft.save
      @draft.update_attributes(user_id: current_user.id)
      redirect_to draft_index_path, success: "L'article a bien été créer"
    else
      render :draft
    end
  end

  def edit_draft
    loggedIn
    @draft = Post.find(params[:id])
  end

  def update_draft
    @draft = Post.find(params[:id])
    post_params = params.require(:post).permit(:title, :content)

    if @draft.update(post_params)
      redirect_to draft_index_path, success: "L'article a bien été édité"
    else
      render :edit_draft
    end
  end

  def publish
    @article = Post.where(user_id: current_user.id).find(params[:id])

    if @article.user_id = current_user.id
      @article.update_attributes(published: 1)
      redirect_to draft_index_path, success: "Votre article a bien été publié il est maintenant en ligne sur le blog", error: "A noter que si l'article n'est pas conforme au site il sera supprimer"
    end
  end

  def unpublish
    @article = Post.where(user_id: current_user.id).find(params[:id])

    if @article
      @article.update_attributes(published: 0)
      redirect_to draft_index_path, success: "Votre article a bien été retirer du blog"
    else
      render "/errors/404"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/draft.html.erb
<%= content_for :mdeditor_css do %>
    <%= stylesheet_link_tag 'mdeditor' %>
<% end %>
<%= content_for :mdeditor_js do %>
    <%= javascript_include_tag 'mdeditor.min' %>
    <script>
      new MdEditor('#post_content', {
          preview: true
      });
    </script>
<% end %>

<h2>Créer un brouillon</h2>

<% if @draft.errors.any? %>
    <div class="alert alert-danger">
      <% @draft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
<% end %>

<%= form_for @draft, url: draft_new_path, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :title, "Titre" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content, "Contenu" %>
      <%= f.text_area :content %>
    </div>
    <div class="form-group">
      <%= f.submit 'Créer', class: 'btn btn-success' %>
    </div>
<% end %>

app/views/posts/draft_index.html.erb
<h2>Mes articles</h2>

<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th style="line-height: 28px;">Titre</th>
    <th><%= link_to 'Ajouter un article', draft_new_path, class: 'btn btn-sm btn-primary' %></th>
  </tr>
  </thead>
  <tbody>
  <% @draft.each do |draft| %>
      <tr>
        <td><%= link_to draft.title, article_path(draft) %></td>
        <td>
          <%= link_to 'Editer', edit_draft_path(draft.id) %> -
          <% if draft.published != 1 %>
              <%= link_to 'Publier', publish_draft_path(draft.id) %> -
          <% else %>
              <%= link_to 'Retirer l\'article', unpublish_draft_path(draft.id), method: :delete, data: {confirm: "Êtes vous sûr de vouloir retirer l'article ?"} %> -
          <% end %>
          <%= link_to 'Supprimer', dra_path(draft.id), method: :delete, data: {confirm: 'Are you sûre?'}, :class => 'btn-delete' %>
        </td>
      </tr>
  <% end %>
  </tr>
  </tbody>
</table>

<div class="modals" id="modal">
  <div class="modals__content">
    <header>
      <p class="content"></p>
    </header>
    <div class="pull-left">
      <a href="#" class="btn btn-success data-url">Oui</a>
    </div>
    <div class="pull-right">
      <a href="#" class="btn btn-danger btn-close">Non</a>
    </div>
  </div>
</div>

app/views/posts/edit_draft.html.erb
<%= content_for :mdeditor_css do %>
    <%= stylesheet_link_tag 'mdeditor' %>
<% end %>
<%= content_for :mdeditor_js do %>
    <%= javascript_include_tag 'mdeditor.min' %>
    <script>
        new MdEditor('#post_content', {
            preview: true
        });
    </script>
<% end %>

<h2>Editer l'article</h2>

<% if @draft.errors.any? %>
    <div class="alert alert-danger">
      <% @draft.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </div>
<% end %>

<%= form_for @draft, url: edit_draft_path do |f| %>
    <div class="form-group">
      <%= f.label :title, "Titre" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content, "Contenu" %>
      <%= f.text_area :content %>
    </div>
    <div class="form-group">
      <%= f.submit 'Mettre à jour', class: 'btn btn-success' %>
    </div>
<% end %>