config/routes.rb
Rails.application.routes.draw do

  # HomePage
  root to: 'home#index'

  # Articles page/Création de brouillon
  resources :blog, as: :articles, controller: 'articles', only: [:index, :show]
  scope '/draft' do
    get '/', to: 'posts#draft_index', as: :draft_index

    get '/new', to: 'posts#draft', as: :draft_new
    post '/new', to: 'posts#create_draft'

    get '/:id/edit', to: 'posts#edit_draft', as: :edit_draft
    patch '/:id/edit', to: 'posts#update_draft'

    get '/:id/publish', to: 'posts#publish', as: :publish_draft
    get '/:id/unpublish', to: 'posts#unpublish', as: :unpublish_draft
  end
  # Supression des brouillon
  get '/drafts/:id', to: 'drafts#destroy', as: :dra

  #Inscription, connexion et déconnexion des utilisateurs
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: :logout_session
  match '/forgot', to: 'sessions#forgot', as: :forgot, via: [:get, :post]
  match '/password/new', to: 'sessions#password', as: :forgot_success, via: [:get, :post]
  resources :users, only: [:new, :create]

  scope '/profil' do
    get '/', to: 'users#account', as: :profil

    get '/edit', to: 'users#edit', as: :edit_user
    patch '/edit', to: 'users#update'

    get '/:id', to: 'users#show', as: :view_user
  end

  scope '/dashboard', as: :admin do
    get '/', to: 'admin/pages#index', as: :index
    resources :articles, controller: 'admin/posts'
    resources :tutoriels, controller: 'admin/tutoriels'
  end

  scope '/blog' do
    get '/like/:post_id/:user_id', to: 'articles#like', as: :likes
    get '/unlike/:id/:post_id', to: 'articles#unlike', as: :unlikes
    post '/:slug', to: 'articles#create_comment', as: :new_comment
    get '/comment/like/:comment_id/:post_id', to: 'articles#like_comment', as: :like_comment
    get '/comment/unlike/:comment_id/:post_id', to: 'articles#unlike_comment', as: :unlike_comment
  end

  get '/tutoriels/:category_name', to: 'tutoriels#show', as: :category_view
  get '/tutoriels/:category/:title', to: 'tutoriels#show_tutoriel', as: :show_tuto
  resources :tutoriels, only: [:index]
end

app/models/tutoriel.rb
class Tutoriel < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :content, presence: true

  belongs_to :category
  belongs_to :user
end

app/controllers/admin/tutoriels_controller.rb
class Admin::TutorielsController < Admin::AdminController

  def index
    @tutoriels = Tutoriel.all
  end

  def show
    redirect_to admin_tutoriel_path
  end

  def new
    @tutoriel = Tutoriel.new
  end

  def create
    @tutoriel = Tutoriel.new(tutoriel_params)

    if @tutoriel.valid?
      @tutoriel.save
      @tutoriel.user_id = current_user.id
      redirect_to admin_tutoriel_path
    else
      render :new
    end
  end

  def edit
    @tutoriel = Tutoriel.find(params[:id])
  end

  def update
    @tutoriel = Tutoriel.find(params[:id])
    if @tutoriel.update(tutoriel_params)
    else
      render :edit
    end
  end

  private

  def tutoriel_params
    params.require(:tutoriel).permit(:title, :user_id, :category_id, :content)
  end
end

app/controllers/tutoriels_controller.rb
class TutorielsController < ApplicationController

  def index
    @tutoriels = Tutoriel.all
  end

  def show
    @category = Category.where(slug: params[:category_name]).first
  end

  def show_tutoriel
    cat = Category.where(slug: params[:category]).first
    @tutoriel = Tutoriel.where(category_id: cat.id).first
  end
end

app/helpers/admin/tutoriels_helper.rb
module Admin::TutorielsHelper
end

app/helpers/tutoriels_helper.rb
module TutorielsHelper
end

app/views/tutoriels/index.html.erb
<h2>Tutoriels</h2>

<div class="row">
  <% @tutoriels.each do |tuto| %>
      <div class="col-sm-4">
        <div class="tutoriel">
          <div class="thumb">
            <%= image_tag 'tutoriels/377_236x144.jpg' %>
          </div>
          <div class="description">
            <span class="title"><%= tuto.title %></span>
            <div class="content">
              <%= truncate(tuto.content, length: 150) %>
            </div>
          </div>
          <div class="footer">
            <span class="category">
              <i class="glyphicon glyphicon-tag"></i>
              <%= tuto.category.title %>
            </span>
            <span class="author">
              <i class="glyphicon glyphicon-user"></i>
              <%= tuto.user.username %>
            </span>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/tutoriels/show.html.erb
<h2><%= @category.title %></h2>

<% @category.tutoriels.each do |post| %>
    <article class="tutoriel">
      <h2><%= post.title %></h2>
      <a href="<%= show_tuto_path(@category.slug, post.slug) %>">Lire la suite</a>
    </article>
<% end %>

app/views/tutoriels/show_tutoriel.html.erb
<ol class="breadcrumb">
  <li>
    <%= link_to 'Accueil', root_path %>
  </li>
  <li>
    <%= link_to 'Tutoriel', tutoriels_path %>
  </li>
  <li>
    <%= link_to @tutoriel.category.title, category_view_path(@tutoriel.category.slug) %>
  </li>
  <li class="active"><%= @tutoriel.title %></li>
</ol>
<article class="tutoriel_view">
  <h2><%= @tutoriel.title %></h2>
  <span class="time">
    <%= time_ago_in_words(@tutoriel.created_at)%>
  </span>
  <span class="author">
    <%= @tutoriel.user.username %>
  </span>
</article>