config/routes.rb
Rails.application.routes.draw do

  # HomePage
  root to: 'home#index'

  # Articles page/Création de brouillon
  resources :blog, as: :articles, controller: 'articles', only: [:index, :show]
  scope '/draft' do
    get '/', to: 'posts#draft_index', as: :draft_index

    get '/new', to: 'posts#draft', as: :draft_new
    post '/new', to: 'posts#create_draft'

    get '/:id/edit', to: 'posts#edit_draft', as: :edit_draft
    patch '/:id/edit', to: 'posts#update_draft'

    get '/:id/publish', to: 'posts#publish', as: :publish_draft
    get '/:id/unpublish', to: 'posts#unpublish', as: :unpublish_draft
  end
  # Supression des brouillon
  get '/drafts/:id', to: 'drafts#destroy', as: :dra

  #Inscription, connexion et déconnexion des utilisateurs
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: :logout_session
  match '/forgot', to: 'sessions#forgot', as: :forgot, via: [:get, :post]
  match '/password/new', to: 'sessions#password', as: :forgot_success, via: [:get, :post]
  resources :users, only: [:new, :create]

  scope '/profil' do
    get '/', to: 'users#account', as: :profil

    get '/edit', to: 'users#edit', as: :edit_user
    patch '/edit', to: 'users#update'

    get '/:id', to: 'users#show', as: :view_user
  end

  scope '/dashboard', as: :admin do
    get '/', to: 'admin/pages#index', as: :index
    resources :articles, controller: 'admin/posts'
    resources :tutoriels, controller: 'admin/tutoriels'
  end

  scope '/blog' do
    get '/like/:post_id/:user_id', to: 'articles#like', as: :likes
    get '/unlike/:id/:post_id', to: 'articles#unlike', as: :unlikes
    post '/:slug', to: 'articles#create_comment', as: :new_comment
    get '/comment/like/:comment_id/:post_id', to: 'articles#like_comment', as: :like_comment
    get '/comment/unlike/:comment_id/:post_id', to: 'articles#unlike_comment', as: :unlike_comment
  end

  get '/tutoriels/:category_name', to: 'tutoriels#show', as: :category_view
  get '/tutoriels/:category/:title', to: 'tutoriels#show_tutoriel', as: :show_tuto
  resources :tutoriels, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :tutoriels
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post, optional: true
  has_many :replies, class_name: "Comment", foreign_key: :parent_id

  validates :content, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord

  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user, optional: true
  has_many :likes
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
end

app/models/tutoriel.rb
class Tutoriel < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :content, presence: true

  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  has_many :tutoriels
  has_many :likes
  has_many :friends

  has_secure_password

  validates :username, presence: true
  validates :email, presence: true

  def to_session
    {id: id}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :loggedIn
  skip_before_action :verify_authenticity_token

  def draft_index
    loggedIn
    @draft = Post.where(user_id: current_user.id)
  end

  def draft
    notAuthorize
    @draft = Post.new
  end

  def create_draft
    post_params = params.require(:post).permit(:title, :content)

    @draft = Post.new(post_params)

    if @draft.valid?
      @draft.save
      @draft.update_attributes(user_id: current_user.id)
      redirect_to draft_index_path, success: "L'article a bien été créer"
    else
      render :draft
    end
  end

  def edit_draft
    loggedIn
    @draft = Post.find(params[:id])
  end

  def update_draft
    @draft = Post.find(params[:id])
    post_params = params.require(:post).permit(:title, :content)

    if @draft.update(post_params)
      redirect_to draft_index_path, success: "L'article a bien été édité"
    else
      render :edit_draft
    end
  end

  def publish
    @article = Post.where(user_id: current_user.id).find(params[:id])

    if @article.user_id = current_user.id
      @article.update_attributes(published: 1)
      redirect_to draft_index_path, success: "Votre article a bien été publié il est maintenant en ligne sur le blog", error: "A noter que si l'article n'est pas conforme au site il sera supprimer"
    end
  end

  def unpublish
    @article = Post.where(user_id: current_user.id).find(params[:id])

    if @article
      @article.update_attributes(published: 0)
      redirect_to draft_index_path, success: "Votre article a bien été retirer du blog"
    else
      render "/errors/404"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :loggedIn, only: [:account, :edit, :update]

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:username, :email, :password, :password_confirmation)
    @user = User.new(user_params)

    if @user.valid?
      @user.save
      redirect_to new_session_path, success: "Votre compte a bien été créer"
    else
      render :new
    end
  end


  def account
    @like = Like.where(user_id: current_user)
  end

  def edit
    loggedIn
    @user = current_user
  end

  def update
    @user = current_user

    user_params = params.require(:user).permit(:email, :firstname, :lastname, :secret)

    if @user.update(user_params)
      redirect_to profil_path, success: "Votre compte a bien été mis à jour"
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tutoriels_helper.rb
module TutorielsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/index.html.erb
<h2>Administration</h2>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>Administration</title>
  <%= stylesheet_link_tag 'admin', 'ionicons' %>
  <%= yield(:mdeditor_css) %>
</head>
<body>
<header class="header">
  <div class="logo">
    <i class="ion-code-working"></i>
    <p>
      Admin
      <string>Istration</string>
    </p>
  </div>
  <div class="header-content" id="head-content">
    <div class="breadcrumb" id="breadcrumb">
      <div class="br-content">
        <span class="home">
          <%= link_to 'Administration', admin_index_path %>
        </span>
      </div>
    </div>
    <div class="search-form"></div>
    <div class="account" id="account">
      <%= image_tag 'https://www.myrouteapp.com/images/icons/default-avatar.png' %>
      <i class="ion-chevron-down"></i>
    </div>
    <div class="topmenu hide" id="topbar-menu">
      <%= link_to root_path do %>
        <i class="ion-link"></i>
        Voir le site
      <% end %>
    </div>
  </div>
</header>
<div class="nav-button-responsive" id="nav-button-responsive">
  <i class="ion-navicon-round"></i>
</div>
<div class="nav" id="nav">
  <div class="menu">
    <%= link_to admin_index_path do %>
        <i class="ion-home"></i> <span>Administration</span>
    <% end %>
    <%= link_to admin_articles_path do %>
        <i class="ion-document"></i> <span>Articles</span>
    <% end %>
    <%= link_to admin_tutoriels_path do %>
        <i class="ion-code-working"></i> <span>Tutoriels</span>
    <% end %>
  </div>
</div>
<div class="content">
  <%= yield %>
</div>
<div class="footer"></div>
<%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js', 'admin', 'app' %>
<%= yield(:mdeditor_js) %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'bootstrap', 'app' %>
    <%= yield(:mdeditor_css) %>
  </head>

  <body>
  <div class="navbar navbar-static-top navbar-inverse" id="topbar">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Finals', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Accueil', root_path %></li>
        <li><%= link_to 'Blog', articles_path %></li>
        <li><%= link_to 'Tutoriels', tutoriels_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Bonjour, <%= current_user.username; %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.role == 'admin' %>
                <li>
                  <a href="<%= url_for admin_index_path %>">
                    <i class="glyphicon glyphicon-dashboard"></i>
                    Administration
                  </a>
                </li>
              <% end %>
              <li>
                <a href="<%= url_for profil_path %>">
                  <i class="glyphicon glyphicon-user"></i>
                  Mon compte
                </a>
              </li>
              <li>
                <a href="<%= url_for draft_index_path %>">
                  <i class="glyphicon glyphicon-inbox"></i>
                  Mes articles
                </a>
              </li>
              <li class="divider"></li>
              <li><a href="<%= url_for logout_session_path %>">
                <i class="glyphicon glyphicon-log-out"></i>
                Se déconnecter
              </a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "S'inscrire", new_user_path %></li>
          <li><%= link_to "Se connecter", new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
    <div class="container" id="container">
      <% if flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <% end %>
      <% if flash[:error] %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <%= javascript_include_tag 'bootstrap', 'app', 'drafts' %>
  <%= yield(:mdeditor_js) %>
  </body>
</html>